[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rota"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Seu Nome", email = "seuemail@example.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.3.4",
    "pyyaml>=6.0.2",
]

[project.scripts]
rota = "rota.hello:main"
